[build]
command = "npm run build"
publish = "build"
functions = ".netlify/functions/"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/.netlify/functions/render"
status = 200